variable "fullcompanyname" {}
variable "shortcompanyname" {}
variable "location" {}
variable "dc_size" {}
variable "key_vault_id" {}
variable "resource_group" {}
variable "subnet" {}
variable "storage" {}
variable "hub_vnet" {}